language: python

sudo: required
dist: trusty


python:
  - "3.5"

cache: pip

before_install:


install:
  - pip install coveralls

env:
  - PYTHONPATH=$PYTHONPATH:/opt/mantidnightly/bin

script:

  - python setup.py nosetests

after_success:
- coveralls