language: python

sudo: required
dist: trusty


python:
  - "3.5"

cache: pip

before_install:


install:
  - pip install nose

env:
  - PYTHONPATH=$PYTHONPATH:/home/travis/build/EltayebAhmed/scc/


script:
  - nosetests tests/

