language: python

sudo: required
dist: trusty


python:
  - "3.5"

cache: pip

before_install:


install:
  - pip install nosetests

env:
  - PYTHONPATH=$PYTHONPATH:/opt/mantidnightly/bin

script:
  - nosetests tests/

